name: gosti_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  country_code_picker: ^2.0.1
  curved_navigation_bar: ^1.0.1

  dio: ^4.0.0
  
  flutter_bloc: ^7.0.0
  flutter_credit_card_detector: ^2.0.0
  flutter_html: ^2.1.1  
  flutter_masked_text2: ^0.9.1

  font_awesome_flutter: ^9.0.0
  formz: ^0.4.0

  geolocator: ^7.6.2
  get: ^4.3.8
  google_fonts: ^2.1.0

  http: ^0.13.4

  mask_text_input_formatter: ^2.0.0-nullsafety.2
  mercadopago_sdk: ^1.3.0
  mercadopago_transparent: ^1.0.1

  pin_code_fields: ^7.0.0

  scrollable_list_tabview: ^0.2.0-nullsafety
  shared_preferences: ^2.0.8

  url_launcher: ^6.0.9

  webview_flutter: ^2.0.10

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/